postfix-3.2-20170108-nonprod

diff --git a/postfix/src/postmap/Makefile.in b/postfix/src/postmap/Makefile.in
--- a/postfix/src/postmap/Makefile.in
+++ b/postfix/src/postmap/Makefile.in
@@ -26,41 +26,48 @@ update: ../../bin/$(PROG)
 ../../bin/$(PROG): $(PROG)
 	cp $(PROG) ../../bin
 
-tests:	test1 test2 fail_test
+tests:	test1 test2 fail_test quote_test
 
 root_tests:
 
 test1:	$(PROG) map.in map-abc1.ref map-ghi1.ref map-uABC1.ref
-	./$(PROG) map.in
+	$(SHLIB_ENV) ./$(PROG) map.in
 	for key in abc ghi; \
 	do \
-	    ./$(PROG) -q $${key} map.in | diff map-$${key}1.ref -; \
+	    $(SHLIB_ENV) ./$(PROG) -q $${key} map.in | diff map-$${key}1.ref -; \
 	done
-	./$(PROG) -f map.in
+	$(SHLIB_ENV) ./$(PROG) -f map.in
 	for key in ABC; \
 	do \
-	    ./$(PROG) -fq $${key} map.in | diff map-u$${key}1.ref -; \
+	    $(SHLIB_ENV) ./$(PROG) -fq $${key} map.in | diff map-u$${key}1.ref -; \
 	done
 	rm -f map.in.db
 
 test2:	$(PROG) map.in map-abc2.ref map-ghi2.ref map-uABC2.ref
-	./$(PROG) map.in
+	$(SHLIB_ENV) ./$(PROG) map.in
 	for key in abc ghi; \
 	do \
-	    echo $${key} | ./$(PROG) -q - map.in | diff map-$${key}2.ref -; \
+	    echo $${key} | $(SHLIB_ENV) ./$(PROG) -q - map.in | diff map-$${key}2.ref -; \
 	done
-	./$(PROG) -f map.in
+	$(SHLIB_ENV) ./$(PROG) -f map.in
 	for key in ABC; \
 	do \
-	    echo $${key} | ./$(PROG) -fq - map.in | diff map-u$${key}2.ref -; \
+	    echo $${key} | $(SHLIB_ENV) ./$(PROG) -fq - map.in | diff map-u$${key}2.ref -; \
 	done
 	rm -f map.in.db
 
 fail_test: $(PROG) aliases fail_test.in fail_test.ref
-	-(sh fail_test.in || exit 0) 2>&1 | \
-	    sed 's/No error:/Unknown error:/' > fail_test.tmp
+	-($(SHLIB_ENV) sh fail_test.in || exit 0) 2>&1 | \
+	    sed -e 's/No error:/Unknown error:/' \
+		-e 's/Success/Unknown error: 0/' > fail_test.tmp
 	diff fail_test.ref fail_test.tmp
 	rm -f fail_test.tmp
+
+quote_test: $(PROG) aliases quote_test.in quote_test.ref
+	rm -f quote_test_map.*
+	$(SHLIB_ENV) sh quote_test.in >quote_test.tmp 2>&1
+	diff quote_test.ref quote_test.tmp
+	rm -f quote_test.tmp quote_test_map.*
 
 printfck: $(OBJS) $(PROG)
 	rm -rf printfck
@@ -73,7 +80,7 @@ lint:
 	lint $(DEFS) $(SRCS) $(LINTFIX)
 
 clean:
-	rm -f *.o *core $(PROG) $(TESTPROG) junk map.in.db
+	rm -f *.o *core $(PROG) $(TESTPROG) *.tmp junk *.db
 	rm -rf printfck
 
 tidy:	clean
@@ -105,6 +112,8 @@ postmap.o: ../../include/msg_syslog.h
 postmap.o: ../../include/msg_vstream.h
 postmap.o: ../../include/myflock.h
 postmap.o: ../../include/mymalloc.h
+postmap.o: ../../include/quote_822_local.h
+postmap.o: ../../include/quote_flags.h
 postmap.o: ../../include/readlline.h
 postmap.o: ../../include/rec_type.h
 postmap.o: ../../include/set_eugid.h
