postfix-2.12-20140921

diff --git a/postfix/src/postconf/Makefile.in b/postfix/src/postconf/Makefile.in
--- a/postfix/src/postconf/Makefile.in
+++ b/postfix/src/postconf/Makefile.in
@@ -49,7 +49,7 @@ tests: test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 test11 \
 	test22 test23 test24 test25 test26 test27 test28 test29 test30 test4b \
 	test31 test32 test33 test34 test35 test36 test37 test39 test40 test41 \
 	test42 test43 test44 test45 test46 test47 test48 test49 test50 test51 \
-	test52 test53 test54 test55 test56
+	test52 test53 test54 test55 test56 test57 test58
 
 root_tests:
 
@@ -72,6 +72,7 @@ test1:	$(PROG) test1.ref
 	touch main.cf master.cf
 	echo smtpd_restriction_classes = foo bar >> main.cf
 	echo foo = yes >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test1.tmp 2>&1
 	diff test1.ref test1.tmp
 	rm -f main.cf master.cf test1.tmp
@@ -83,6 +84,7 @@ test2:	$(PROG) test2.ref
 	touch main.cf master.cf
 	echo restriction_classes = foo bar >> main.cf
 	echo foo = yes >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test2.tmp 2>&1
 	diff test2.ref test2.tmp
 	rm -f main.cf master.cf test2.tmp
@@ -95,6 +97,7 @@ test3:	$(PROG) test3.ref
 	echo foo = yes >> main.cf
 	echo 'bar = $$foo' >> main.cf
 	echo 'always_bcc = $$bar' >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test3.tmp 2>&1
 	diff test3.ref test3.tmp
 	rm -f main.cf master.cf test3.tmp
@@ -108,6 +111,7 @@ test4:	$(PROG) test4.ref
 	echo 'bar = $$foo' >> main.cf
 	echo smtpd unix - n n - 0 smtpd >> master.cf
 	echo ' -o always_bcc=$$bar' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test4.tmp 2>&1
 	diff test4.ref test4.tmp
 	rm -f main.cf master.cf test4.tmp
@@ -123,6 +127,7 @@ test4b:	$(PROG) test4b.ref
 	echo smtpd1 unix - n n - 0 smtpd >> master.cf
 	echo ' -o foo=xxx -o bar=yyy -o baz=zzz' >> master.cf
 	echo '#smtpd2 unix - n n - 0 smtpd' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test4b.tmp 2>&1
 	diff test4b.ref test4b.tmp
 	rm -f main.cf master.cf test4b.tmp
@@ -135,6 +140,7 @@ test5:	$(PROG) test5.ref
 	touch main.cf master.cf
 	echo smtpd unix - n n - 0 smtpd >> master.cf
 	echo ' -o bar=yes -o always_bcc=$$bar -o' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test5.tmp 2>&1
 	diff test5.ref test5.tmp
 	rm -f main.cf master.cf test5.tmp
@@ -145,6 +151,7 @@ test6:	$(PROG) test6.ref
 	rm -f main.cf master.cf
 	touch main.cf master.cf
 	echo whatevershebrings unix - n n - 0 pipe >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -c . 2>&1 | grep whatevershebrings >test6.tmp
 	diff test6.ref test6.tmp
 	rm -f main.cf master.cf test6.tmp
@@ -155,6 +162,7 @@ test7:	$(PROG) test7.ref
 	rm -f main.cf master.cf
 	touch main.cf master.cf
 	echo whatevershebrings unix - n n - 0 spawn >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -c . 2>&1 | grep whatevershebrings >test7.tmp
 	diff test7.ref test7.tmp
 	rm -f main.cf master.cf test7.tmp
@@ -164,6 +172,7 @@ test8:	$(PROG) test8.ref
 	touch main.cf master.cf
 	echo whatevershebrings inet - n n - 0 spawn >> master.cf
 	echo whatevershebrings_time_limit=1 >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -c . 2>&1 | grep whatevershebrings >test8.tmp
 	diff test8.ref test8.tmp
 	rm -f main.cf master.cf test8.tmp
@@ -173,6 +182,7 @@ test9:	$(PROG) test9.ref
 	touch main.cf master.cf
 	echo foo inet - n n - 0 spawn >> master.cf
 	echo bar unix - n n - 0 spawn >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -c . -M '*'/inet >test9.tmp 2>&1
 	diff test9.ref test9.tmp
 	rm -f main.cf master.cf test9.tmp
@@ -182,6 +192,7 @@ test10:	$(PROG) test10.ref
 	touch main.cf master.cf
 	echo foo inet - n n - 0 spawn >> master.cf
 	echo bar unix - n n - 0 spawn >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -c . -M bar/inet foo/unix >test10.tmp 2>&1
 	diff test10.ref test10.tmp
 	rm -f main.cf master.cf test10.tmp
@@ -191,6 +202,7 @@ test11:	$(PROG) test11.ref
 	touch main.cf master.cf
 	echo foo inet - n n - 0 spawn >> master.cf
 	echo bar unix - n n - 0 spawn >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -c . -M >test11.tmp 2>&1
 	diff test11.ref test11.tmp
 	rm -f main.cf master.cf test11.tmp
@@ -205,6 +217,7 @@ test12:	$(PROG) test12.ref
 	echo ' -o always_bcc=$$bar -o' >> master.cf
 	echo foo inet - n n - 0 spawn >> master.cf
 	echo ' -o always_bcc=$$bar -o' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -c . -M >test12.tmp 2>&1
 	diff test12.ref test12.tmp
 	rm -f main.cf master.cf test12.tmp
@@ -218,6 +231,7 @@ test13:	$(PROG) test13.ref
 	echo baz=xx >> main.cf
 	echo foo inet - n n - 0 spawn >> master.cf
 	echo ' -o smtpd_restriction_classes=bar' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test13.tmp 2>&1
 	diff test13.ref test13.tmp
 	rm -f main.cf master.cf test13.tmp
@@ -230,6 +244,7 @@ test14:	$(PROG) test14.ref
 	echo smtpd_restriction_classes=bar >> main.cf
 	echo foo inet - n n - 0 spawn >> master.cf
 	echo ' -o bar=yes -o baz=xx' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test14.tmp 2>&1
 	diff test14.ref test14.tmp
 	rm -f main.cf master.cf test14.tmp
@@ -243,6 +258,7 @@ test15:	$(PROG) test15.ref
 	echo baz=yy >> main.cf
 	echo foo inet - n n - 0 spawn >> master.cf
 	echo ' -o bar=yes -o always_bcc=$$bar$$baz' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test15.tmp 2>&1
 	diff test15.ref test15.tmp
 	rm -f main.cf master.cf test15.tmp
@@ -251,14 +267,14 @@ test15:	$(PROG) test15.ref
 
 test16:	$(PROG) test16.ref
 	rm -f main.cf master.cf
-	touch main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test16.tmp 2>&1
 	diff test16.ref test16.tmp
 	rm -f main.cf master.cf test16.tmp
 
 test17:	$(PROG) test17.ref
 	rm -f main.cf master.cf
-	touch main.cf
+	touch -t 197101010000 main.cf
 	-./$(PROG) -Mc . >test17.tmp 2>&1; exit 0
 	diff test17.ref test17.tmp
 	rm -f main.cf master.cf test17.tmp
@@ -270,6 +286,7 @@ test18:	$(PROG) test18.ref
 	touch main.cf master.cf
 	echo virtual_maps=xxx >> main.cf
 	echo smtpd_client_connection_limit_exceptions=yyy >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test18.tmp 2>&1
 	diff test18.ref test18.tmp
 	rm -f main.cf master.cf test18.tmp
@@ -281,6 +298,7 @@ test19:	$(PROG) test19.ref
 	touch main.cf master.cf
 	echo forward_path='$$'aaaa >> main.cf
 	echo default_rbl_reply='$$'bbbb >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test19.tmp 2>&1
 	diff test19.ref test19.tmp
 	rm -f main.cf master.cf test19.tmp
@@ -292,6 +310,7 @@ test20:	$(PROG) test20.ref
 	touch main.cf master.cf
 	echo foo inet - n n - 0 spawn >> master.cf
 	echo ' -o always_bcc=$$bar$$baz' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Mfc . >test20.tmp 2>&1
 	diff test20.ref test20.tmp
 	rm -f main.cf master.cf test20.tmp
@@ -303,6 +322,7 @@ test21:	$(PROG) test21.ref
 	touch main.cf master.cf
 	echo forward_path = xxxxxxxxxxxxx xxxxxxxxxxxxxx xxxxxxxxxxxx \
 	    xxxxxxxxxxxxx xxxxxxxxxxxxxx >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nfc . >test21.tmp 2>&1
 	diff test21.ref test21.tmp
 	rm -f main.cf master.cf test21.tmp
@@ -313,6 +333,7 @@ test22:	$(PROG) test22.ref
 	rm -f main.cf master.cf
 	touch main.cf master.cf
 	echo whatevershebrings unix - n n - 0 smtp >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -c . 2>&1 | grep whatevershebrings >test22.tmp
 	diff test22.ref test22.tmp
 	rm -f main.cf master.cf test22.tmp
@@ -326,6 +347,7 @@ test23:	$(PROG) test23.ref
 	echo name = value >> main.cf
 	echo whatevershebrings unix - n n - 0 smtp >> master.cf
 	echo ' -o always_bcc=$$name' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -c . -nC builtin >test23.tmp 2>&1
 	diff test23.ref test23.tmp
 	rm -f main.cf master.cf test23.tmp
@@ -337,6 +359,7 @@ test24:	$(PROG) test24.ref
 	echo name = value >> main.cf
 	echo whatevershebrings unix - n n - 0 smtp >> master.cf
 	echo ' -o always_bcc=$$name' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -c . -nC user >test24.tmp 2>&1
 	diff test24.ref test24.tmp
 	rm -f main.cf master.cf test24.tmp
@@ -348,6 +371,7 @@ test25:	$(PROG) test25.ref
 	echo name = value >> main.cf
 	echo whatevershebrings unix - n n - 0 smtp >> master.cf
 	echo ' -o always_bcc=$$name' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -c . -C service 2>&1 | grep whatevershebrings >test25.tmp
 	diff test25.ref test25.tmp
 	rm -f main.cf master.cf test25.tmp
@@ -361,6 +385,7 @@ test26:	$(PROG) test26.ref
 	echo name = value >> main.cf
 	echo whatevershebrings unix - n n - 0 smtp >> master.cf
 	echo ' -o always_bcc=$$name' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . -C all >test26.tmp 2>&1
 	diff test26.ref test26.tmp
 	rm -f main.cf master.cf test26.tmp
@@ -372,6 +397,7 @@ test27:	$(PROG) test27.ref
 	echo name = value >> main.cf
 	echo whatevershebrings unix - n n - 0 smtp >> master.cf
 	echo ' -o always_bcc=$$name' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -c . -C all 2>&1 | grep whatevershebrings >test27.tmp
 	diff test27.ref test27.tmp
 	rm -f main.cf master.cf test27.tmp
@@ -392,6 +418,7 @@ test28:	$(PROG) test28.ref
 	echo ' -o body_checks=$$db:zz' >> master.cf
 	echo 'zz_domain = whatever' >> main.cf
 	echo 'aa_domain = whatever' >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test28.tmp 2>&1
 	diff test28.ref test28.tmp
 	rm -f main.cf master.cf test28.tmp
@@ -416,6 +443,7 @@ test29:	$(PROG) test29.ref
 	echo 'memcachexx = proxy:memcache:memcachefoo' >> main.cf
 	echo 'memcachefoo_domain = bar' >> main.cf
 	echo 'memcachefoo_domainx = bar' >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test29.tmp 2>&1
 	diff test29.ref test29.tmp
 	rm -f main.cf master.cf test29.tmp
@@ -432,6 +460,7 @@ test30:	$(PROG) test30.ref
 	echo ' -o bodyx_checks=$$p2' >> master.cf
 	echo ' -oheader_checks=$$p3' >> master.cf
 	echo ' -oheaderx_checks=$$p4' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nc . >test30.tmp 2>&1
 	diff test30.ref test30.tmp
 	rm -f main.cf master.cf test30.tmp
@@ -443,6 +472,7 @@ test31:	$(PROG) test31.ref
 	touch main.cf master.cf
 	echo 'smtpd_helo_restrictions=whatever' >> main.cf
 	echo 'smtpd_sender_restrictions=$$smtpd_helo_restrictions' >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nxc . >test31.tmp 2>&1
 	diff test31.ref test31.tmp
 	rm -f main.cf master.cf test31.tmp
@@ -453,6 +483,7 @@ test32:	$(PROG) test32.ref
 	rm -f main.cf master.cf
 	touch main.cf master.cf
 	echo 'relay_domains=whatever' >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -xc . fast_flush_domains >test32.tmp 2>&1
 	diff test32.ref test32.tmp
 	rm -f main.cf master.cf test32.tmp
@@ -464,6 +495,7 @@ test33:	$(PROG) test33.ref
 	touch main.cf master.cf
 	echo 'mydestination=whatever' >> main.cf
 	echo 'always_bcc=$$relay_domains' >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -xc . always_bcc >test33.tmp 2>&1
 	diff test33.ref test33.tmp
 	rm -f main.cf master.cf test33.tmp
@@ -474,6 +506,7 @@ test34:	$(PROG) test34.ref
 	echo 'mydestination=whatever' >> main.cf
 	echo 'process_name=xxx' >> main.cf
 	echo 'process_id=yyy' >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -xc . mydestination process_name >test34.tmp 2>&1
 	diff test34.ref test34.tmp
 	rm -f main.cf master.cf test34.tmp
@@ -485,6 +518,7 @@ test35:	$(PROG) test35.ref
 	echo ' -o body_checks=whatever' >> master.cf
 	echo ' -o process_name=aaa' >> master.cf
 	echo ' -o process_id=bbb' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -xc . process_name >test35.tmp 2>&1
 	diff test35.ref test35.tmp
 	rm -f main.cf master.cf test35.tmp
@@ -494,6 +528,7 @@ test36:	$(PROG) test36.ref
 	touch main.cf master.cf
 	echo 'mydestination=$$virtual_mapx' >> main.cf
 	echo 'virtual_alias_maps=$$virtual_maps' >> main.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -nxc . >test36.tmp 2>&1
 	diff test36.ref test36.tmp
 	rm -f main.cf master.cf test36.tmp
@@ -507,6 +542,7 @@ test37: $(PROG) test37.ref
 	echo ' -o mydestination=$$xxx' >> master.cf
 	echo ' -o always_bcc=$$aaa' >> master.cf
 	echo ' -o aaa=ccc' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Mfxc . >test37.tmp 2>&1
 	diff test37.ref test37.tmp
 	rm -f main.cf master.cf test37.tmp
@@ -517,6 +553,7 @@ test39: $(PROG) test39.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar inet - n n - 0 other >> master.cf
 	echo baz unix - n n - 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Mfc . '*'/unix >test39.tmp 2>&1
 	diff test39.ref test39.tmp
 	rm -f main.cf master.cf test39.tmp
@@ -528,6 +565,7 @@ test40: $(PROG) test40.ref
 	echo ' -voaaa=bbb' >> master.cf
 	echo ' -vo ccc=$$aaa' >> master.cf
 	echo ' -v -oddd=$$ccc' >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Mfxc . '*'/unix >test40.tmp 2>&1
 	diff test40.ref test40.tmp
 	rm -f main.cf master.cf test40.tmp
@@ -538,6 +576,7 @@ test41: $(PROG) test41.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar unix - n n - 0 other >> master.cf
 	echo baz unix - n n - 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Pc . bar/unix/xxx=yyy bar/unix/aaa=bbb >test41.tmp 2>&1
 	./$(PROG) -Mfc. >>test41.tmp 2>&1
 	./$(PROG) -Pc . bar/unix/xxx=YYY bar/unix/aaa=BBB >>test41.tmp 2>&1
@@ -552,6 +591,7 @@ test42: $(PROG) test42.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar unix - n n - 0 other >> master.cf
 	echo baz unix - n n - 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Pc . bar/unix/xxx=yyy bar/unix/aaa=bbb >test42.tmp 2>&1
 	./$(PROG) -Mfc. >>test42.tmp 2>&1
 	./$(PROG) -Pc . >>test42.tmp 2>&1
@@ -566,6 +606,7 @@ test43: $(PROG) test43.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar unix - n n - 0 other >> master.cf
 	echo baz unix - n n - 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Fc . bar/unix/chroot=y bar/unix/command='aa -stuffobb=cc dd' >test43.tmp 2>&1
 	./$(PROG) -Mfc. >>test43.tmp 2>&1
 	diff test43.ref test43.tmp
@@ -577,6 +618,7 @@ test44: $(PROG) test44.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar unix - n n - 0 other >> master.cf
 	echo baz unix - n n - 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Mc . bar/unix='xx inet - n n - 0 aa -stuffobb=cc dd' >test44.tmp 2>&1
 	./$(PROG) -Mfc. >>test44.tmp 2>&1
 	diff test44.ref test44.tmp
@@ -588,6 +630,7 @@ test45: $(PROG) test45.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar xxxx - n n - 0 other >> master.cf
 	echo baz unix - n n - 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Mfc. >test45.tmp 2>&1 || true
 	diff test45.ref test45.tmp
 	rm -f main.cf master.cf test45.tmp
@@ -598,6 +641,7 @@ test46: $(PROG) test46.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar inet X n n - 0 other >> master.cf
 	echo baz unix - n n - 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Mfc. >test46.tmp 2>&1 || true
 	diff test46.ref test46.tmp
 	rm -f main.cf master.cf test46.tmp
@@ -608,6 +652,7 @@ test47: $(PROG) test47.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar inet - X n - 0 other >> master.cf
 	echo baz unix - n n - 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Mfc. >test47.tmp 2>&1 || true
 	diff test47.ref test47.tmp
 	rm -f main.cf master.cf test47.tmp
@@ -618,6 +663,7 @@ test48: $(PROG) test48.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar inet - n X - 0 other >> master.cf
 	echo baz unix - n n - 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Mfc. >test48.tmp 2>&1 || true
 	diff test48.ref test48.tmp
 	rm -f main.cf master.cf test48.tmp
@@ -628,6 +674,7 @@ test49: $(PROG) test49.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar inet - n n X 0 other >> master.cf
 	echo baz unix - n n - 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Mfc. >test49.tmp 2>&1 || true
 	diff test49.ref test49.tmp
 	rm -f main.cf master.cf test49.tmp
@@ -638,6 +685,7 @@ test50: $(PROG) test50.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar inet - n n - X other >> master.cf
 	echo baz unix - n n - 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Mfc. >test50.tmp 2>&1 || true
 	diff test50.ref test50.tmp
 	rm -f main.cf master.cf test50.tmp
@@ -648,6 +696,7 @@ test51: $(PROG) test51.ref
 	echo foo unix - n n -? 0 other >> master.cf
 	echo bar inet - n n X? 0 other >> master.cf
 	echo baz unix - n n 0? 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -Mfc. >test51.tmp 2>&1 || true
 	diff test51.ref test51.tmp
 	rm -f main.cf master.cf test51.tmp
@@ -658,6 +707,7 @@ test52: $(PROG) test52.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar inet - n n 0 0 other >> master.cf
 	echo baz unix - n n 0 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -MXc. bar/inet foo/unix xxx/yyy
 	./$(PROG) -Mfc. >test52.tmp 2>&1 || true
 	diff test52.ref test52.tmp
@@ -669,6 +719,7 @@ test53: $(PROG) test53.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar inet - n n 0 0 other >> master.cf
 	echo baz unix - n n 0 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -M#c. bar/inet xxx/yyy
 	diff test53.ref master.cf
 	rm -f main.cf master.cf test53.tmp
@@ -679,6 +730,7 @@ test54: $(PROG) test54.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar inet - n n 0 0 other >> master.cf
 	echo baz unix - n n 0 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -M#c. bar/inet foo/unix
 	diff test54.ref master.cf
 	rm -f main.cf master.cf test54.tmp
@@ -689,6 +741,7 @@ test55: $(PROG) test55.ref
 	echo foo unix - n n - 0 other >> master.cf
 	echo bar inet - n n 0 0 other >> master.cf
 	echo baz unix - n n 0 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -M#c. bar/inet baz/unix
 	diff test55.ref master.cf
 	rm -f main.cf master.cf test55.tmp
@@ -701,9 +754,40 @@ test56: $(PROG) test56.ref
 	echo " -o first" >> master.cf
 	echo " -o second" >> master.cf
 	echo baz unix - n n 0 0 other >> master.cf
+	touch -t 197101010000 main.cf
 	./$(PROG) -M#c. bar/inet xxx/yyy
 	diff test56.ref master.cf
 	rm -f main.cf master.cf test56.tmp
+
+# Many more tests in util/mac_expand.in.
+
+test57: $(PROG) test57.ref
+	rm -f main.cf master.cf
+	touch main.cf master.cf
+	echo 'x = $${{1} == {2}?{error}:x-value}' >> main.cf
+	echo 'y = y-value' >> main.cf
+	echo 'bar = $${x?{$$y}:$$z}' >> main.cf
+	echo 'baz = $${x?{$$z}:$$y}' >> main.cf
+	echo 'foo = $$bar$$baz' >> main.cf
+	echo 't1 = Postfix 2.11 $${{$${x?bug:x}} == {bug}?in}compatible' >> main.cf
+	echo 't2 = $$t1' >> main.cf
+	touch -t 197101010000 main.cf
+	./$(PROG) -nxc. >test57.tmp 2>&1
+	diff test57.ref test57.tmp
+	rm -f main.cf master.cf test57.tmp
+
+test58: $(PROG) test58.ref
+	rm -f main.cf master.cf
+	touch main.cf master.cf
+	echo 'mydestination = foo bar pipemap:{ldap:xxx, memcache:yy} randmap:{xx' >> main.cf
+	echo 'xxx_domain = foo' >> main.cf
+	echo 'xxx_bogus = foo' >> main.cf
+	echo 'yy_backup = bbb' >> main.cf
+	echo 'yy_bogus = bbb' >> main.cf
+	touch -t 197101010000 main.cf
+	$(SHLIB_ENV) ./postconf -nc. >test58.tmp 2>&1 || true
+	diff test58.ref test58.tmp
+	rm -f main.cf master.cf test58.tmp
 
 printfck: $(OBJS) $(PROG)
 	rm -rf printfck
@@ -812,6 +896,8 @@ postconf_dbms.o: ../../include/htable.h
 postconf_dbms.o: ../../include/mac_expand.h
 postconf_dbms.o: ../../include/mac_parse.h
 postconf_dbms.o: ../../include/mail_conf.h
+postconf_dbms.o: ../../include/mail_params.h
+postconf_dbms.o: ../../include/msg.h
 postconf_dbms.o: ../../include/myflock.h
 postconf_dbms.o: ../../include/name_code.h
 postconf_dbms.o: ../../include/split_at.h
