postfix-2.2-20040917

diff --git a/postfix/makedefs b/postfix/makedefs
--- a/postfix/makedefs
+++ b/postfix/makedefs
@@ -52,6 +52,19 @@ SYSLIBS=
 AR=ar
 ARFL=rv
 
+# Ugly function to make our error message more visible among the
+# garbage that is output by some versions of make(1).
+
+# By now all shells must have functions.
+
+error() {
+   # Alas, tput(1) is not portable so we can't use visual effects.
+   echo "ATTENTION:" 1>&2;
+   echo "ATTENTION:" $* 1>&2;
+   echo "ATTENTION:" 1>&2;
+   exit 1
+}
+
 SYSTEM=`(uname -s) 2>/dev/null`
 RELEASE=`(uname -r) 2>/dev/null`
 VERSION=`(uname -v) 2>/dev/null`
@@ -81,8 +94,7 @@ case "$SYSTEM.$RELEASE" in
 		    RANLIB=echo
 		    SYSLIBS="-lresolv -lsocket -lnsl -lc -L/usr/ucblib -lucb"
 		    ;;
-	      *) echo "Seems to be UnixWare`uname -v`. Untested." 1>&2; 
-		 exit 1;;
+	      *) error "Seems to be UnixWare`uname -v`. Untested.";;
 		esac
 		;;
   FreeBSD.2*)	SYSTYPE=FREEBSD2
@@ -135,12 +147,12 @@ case "$SYSTEM.$RELEASE" in
 		STRCASE="strcasecmp.o"
 		# Avoid common types of braindamage
 		case "$LD_LIBRARY_PATH" in
-		?*) echo "Don't set LD_LIBRARY_PATH" 1>&2; exit 1;;
+		?*) error "Don't set LD_LIBRARY_PATH";;
 		esac
-		case "$CC" in
-		*ucb*) echo "Don't use /usr/ucb/cc or ucblib" 1>&2; exit 1;;
-		  cc*) case `which cc` in
-		*ucb*) echo "Don't use /usr/ucb/cc or ucblib" 1>&2; exit 1;;
+		case "${CC}" in
+		*ucb*) error "Don't use /usr/ucb/cc or ucblib";;
+		  cc*) case `which ${CC}` in
+		*ucb*) error "Don't use /usr/ucb/cc or ucblib";;
 		  esac;;
 		esac
 		;;
@@ -179,7 +191,7 @@ case "$SYSTEM.$RELEASE" in
 			esac
 			CCARGS="$CCARGS -D_ALL_SOURCE"
 			;;
-		*)	echo "Unknown AIX version: `uname -v`." 1>&2; exit 1;;
+		*)	error "Unknown AIX version: `uname -v`.";;
 		esac;;
 		# Tested with RedHat 3.03 on 20020729.
     Linux.1*)	SYSTYPE=LINUX1
@@ -297,10 +309,10 @@ Rhapsody.5*|Darwin.*)
 		    : ${CC=cc}
 		    RANLIB="sleep 5; ranlib"
 		else
-		    echo "Unable to determine your system type." 1>&2; exit 1
+		    error "Unable to determine your system type."
 		fi
 		;;
-	   *)	echo "Unknown system type: $SYSTEM $RELEASE" 1>&2; exit 1;;
+	   *)	error "Unknown system type: $SYSTEM $RELEASE";;
 esac
 
 #
@@ -327,7 +339,7 @@ case "$CC" in
 */gcc|gcc) case `$CC -v` in
 	   "gcc version 2.8"*) : ${OPT=};;
 	   esac;;
-      *CC) echo "Don't use CC. That's the C++ compiler" 1>&2; exit 1;;
+      *CC) error "Don't use CC. That's the C++ compiler";;
         *) : ${OPT='-O'};;
 esac
 
