postfix-1.1.6-20020329

diff --git a/postfix/postfix-install b/postfix/postfix-install
--- a/postfix/postfix-install
+++ b/postfix/postfix-install
@@ -88,6 +88,7 @@
 #	The destination directory for Postfix daemon programs. This directory
 #	should not be in the command search path of any users.
 #	The built-in default directory name is /usr/libexec/postfix.
+#	This parameter setting is recorded in the installed main.cf file.
 # .IP command_directory
 #	The destination directory for Postfix administrative commands. This
 #	directory should be in the command search path of adminstrative users.
@@ -173,7 +174,7 @@ do
     case $arg in
       *=*) IFS= eval $arg; IFS="$BACKUP_IFS";;
 -non-int*) non_interactive=1;;
-        *) echo $0: Error: $USAGE 1>&2; exit 1;;
+        *) echo "$0: Error: $USAGE" 1>&2; exit 1;;
     esac
     shift
 done
@@ -530,7 +531,7 @@ MANPAGE_DIRECTORY=$install_root$manpage_directory
 SAMPLE_DIRECTORY=$install_root$sample_directory
 README_DIRECTORY=$install_root$readme_directory
 
-# Avoid repeated tests for existence of these.
+# Avoid repeated tests for existence of these; default permissions suffice.
 
 test -d $DAEMON_DIRECTORY || mkdir -p $DAEMON_DIRECTORY || exit 1
 test -d $COMMAND_DIRECTORY || mkdir -p $COMMAND_DIRECTORY || exit 1
