postfix-3.12-20260406

diff --git a/postfix/README_FILES/TLS_README b/postfix/README_FILES/TLS_README
--- a/postfix/README_FILES/TLS_README
+++ b/postfix/README_FILES/TLS_README
@@ -71,6 +71,7 @@ Topics covered in this section:
   * Server access control
   * Server-side cipher controls
   * Miscellaneous server controls
+  * Testing SNI support
 
 SSeerrvveerr--ssiiddee cceerrttiiffiiccaattee aanndd pprriivvaattee kkeeyy ccoonnffiigguurraattiioonn
 
@@ -746,6 +747,251 @@ behavior with respect to the mask bits. A feature enabled via the mask in one
 release may be enabled by other means in a later release, and the mask bit will
 then be ignored. Therefore, use of the hexadecimal mask is only a temporary
 measure until a new Postfix or OpenSSL release provides a better solution.
+
+TTeessttiinngg SSNNII ssuuppppoorrtt
+
+The Postfix SMTP server supports dynamic selection of private keys and
+certificate chains based on the content of the server-name-indication (SNI) TLS
+extension sent by the SMTP client. See the documentation of the
+tls_server_sni_maps configuration parameter for basic syntax details.
+
+Below you'll see how to test SNI support, and, in particular, how to determine
+whether your OpenSSL runtime has been patched to correctly handle SNI with
+recently added public key algorithms, such as the post-quantum MMLL--DDSSAA. Use of
+post-quantum certificates via SNI will become relevant once certification
+authorities start to issue post-quantum certificates. Until then, with self-
+signed certificates, it rarely matters what names happen to appear in a
+certificate that can't be chained to a trusted CA.
+
+First let's check that SNI support works with RSA keys. The below commands will
+generate a key and self-signed certificate:
+
+        # cfdir=$(postconf -dxh config_directory)
+        # cd "$cfdir"
+        # rchain="rsa-test.pem"
+        # fqdn=sni-test.localhost
+        # openssl genpkey -out "$rchain" -algorithm rsa \
+            -pkeyopt rsa_keygen_bits:2048
+        # openssl req -new -x509 -key "$rchain" -subj "/CN=$fqdn" \
+            -addext "basicConstraints = critical,CA:false" \
+            -addext "extendedKeyUsage = serverAuth" \
+            -addext "subjectAltName = DNS:$fqdn" >> "$rchain"
+
+Next, we check that the private key matches the public key in the certificate:
+
+        # cfdir=$(postconf -dxh config_directory)
+        # cd "$cfdir"
+        # rchain=rsa-test.pem
+        # kh=$(openssl pkey -in "$rchain" -pubout -outform DER |
+            openssl dgst -sha256 | sed 's/.*= *//')
+        # xh=$(openssl x509 -in "$rchain" -noout -pubkey |
+            openssl pkey -pubin -outform DER |
+            openssl dgst -sha256 | sed 's/.*= *//')
+        # if [[ "X$kh" == "X$xh" ]] then
+            echo "Equal private and certificate pubkey hashes: $kh"
+          else
+            echo "key does not match certificate in ${rchain}" >&2
+          fi
+
+Next, we construct a test SNI table (as a matter of good habit, making sure it
+is not world-readable), and check that queries return the same public key hash
+as before:
+
+        # cfdir=$(postconf -dxh config_directory)
+        # cd "$cfdir"
+        # rchain=rsa-test.pem
+        # fqdn=sni-test.localhost
+        # dbtype=$(postconf -xh default_database_type)
+        # snitab=sni-test-table
+        # (
+            umask 077
+            printf "%s\t%s\n" "$fqdn" "$cfdir/$rchain" > "$snitab"
+          )
+        # postmap -F "${dbtype}:${snitab}"
+        # postmap -Fq "$fqdn" "${dbtype}:${snitab}" |
+            openssl pkey -pubout -outform DER |
+            openssl dgst -sha256 | sed 's/.*= */pubkey hash: /'
+        # postmap -Fq "$fqdn" "${dbtype}:${snitab}" |
+            openssl x509 -noout -pubkey |
+            openssl pkey -pubin -outform DER |
+            openssl dgst -sha256 | sed 's/.*= */pubkey hash: /'
+
+Next, we add a test SNI-enabled SMTP service on an unused port and loopback IP
+address:
+
+        # cfdir=$(postconf -dxh config_directory)
+        # cd "$cfdir"
+        # rchain=rsa-test.pem
+        # fqdn=sni-test.localhost
+        # dbtype=$(postconf -xh default_database_type)
+        # snitab=sni-test-table
+        # port=$(perl -MIO::Socket -le '
+            # Just pick a "random" unused port if you do not have Perl
+            print IO::Socket::INET->new(
+                Listen => 1,
+                ReuseAddr => 1,
+                LocalHost => "127.0.0.1",
+                LocalPort => 0)->sockport()
+                ')
+        # postconf -M "$(
+            printf '%s/inet = %s inet n - n - - smtpd' \
+                "127.0.0.1:$port" "127.0.0.1:$port"
+            printf '\t-o { tls_server_sni_maps = %s:%s/%s }' \
+                "$dbtype" "$cfdir" "$snitab"
+            printf '\t-o { syslog_name = postfix/sni-test }'
+            )"
+        # postfix reload; sleep 1
+        #
+        # kh=$(openssl pkey -in "$rchain" -pubout -outform DER |
+            openssl dgst -sha256 | sed 's/.*= *//')
+        # ( sleep 1; printf "QUIT\r\n") |
+            openssl s_client -brief -starttls smtp \
+                -connect "127.0.0.1:$port" \
+                -verify 1 -verify_return_error \
+                -dane_tlsa_domain "$fqdn" \
+                -dane_tlsa_rrdata "3 1 1 $kh" &&
+            printf "OK: Got expected SNI chain\n" ||
+            printf "ERROR: Unexpected SNI certificate\n" >&2
+        # postconf -MX "127.0.0.1:$port/inet"
+        # postfix reload
+
+The above basic RSA tests are expected to work, if the instructions are
+followed accurately. If there's an unexpected failure, and the reasons are
+unclear, see the debugging tutorial, for how seek help from the ppoossttffiixx--uusseerrss
+list.
+
+With the basic RSA test out of the way, let's try combining RSA and ECDSA keys:
+
+        # cfdir=$(postconf -dxh config_directory)
+        # cd "$cfdir"
+        # rchain="rsa-test.pem"
+        # echain="ec-test.pem"
+        # rsasig="rsa_pss_rsae_sha256:rsa_pss_rsae_sha384:rsa_pss_rsae_sha512"
+        # rsasig="$rsasig:rsa_pss_pss_sha256:rsa_pss_pss_sha384:
+    rsa_pss_pss_sha512"
+        # rsasig="$rsasig:rsa_pkcs1_sha256:rsa_pkcs1_sha384:rsa_pkcs1_sha512"
+        # ecsig="ecdsa_secp256r1_sha256:ecdsa_secp384r1_sha384:
+    ecdsa_secp521r1_sha512"
+        # fqdn=sni-test.localhost
+        # dbtype=$(postconf -xh default_database_type)
+        # snitab=sni-test-table
+        # openssl genpkey -algorithm rsa -pkeyopt rsa_keygen_bits:2048 \
+            -out "$rchain"
+        # openssl req -new -x509 -key "$rchain" -subj "/CN=$fqdn" \
+            -addext "basicConstraints = critical,CA:false" \
+            -addext "extendedKeyUsage = serverAuth" \
+            -addext "subjectAltName = DNS:$fqdn" >> "$rchain"
+        # openssl genpkey -algorithm ec -pkeyopt ec_paramgen_curve:prime256v1 \
+            -out "$echain"
+        # openssl req -new -x509 -key "$echain" -subj "/CN=$fqdn" \
+            -addext "basicConstraints = critical,CA:false" \
+            -addext "extendedKeyUsage = serverAuth" \
+            -addext "subjectAltName = DNS:$fqdn" >> "$echain"
+        # rh=$(openssl pkey -in "$rchain" -pubout -outform DER |
+            openssl dgst -sha256 | sed 's/.*= *//')
+        # eh=$(openssl pkey -in "$echain" -pubout -outform DER |
+            openssl dgst -sha256 | sed 's/.*= *//')
+        # (
+            umask 077
+            printf "%s\t%s, %s\n" \
+                "$fqdn" "$cfdir/$rchain" "$cfdir/$echain" > "$snitab"
+          )
+        # postmap -F "${dbtype}:${snitab}"
+        # port=$(perl -MIO::Socket -le '
+            print IO::Socket::INET->new(
+                Listen => 1,
+                ReuseAddr => 1,
+                LocalHost => "127.0.0.1",
+                LocalPort => 0)->sockport()
+                ')
+        # postconf -M "$(
+            printf '%s/inet = %s inet n - n - - smtpd' \
+                "127.0.0.1:$port" "127.0.0.1:$port"
+            printf '\t-o { tls_server_sni_maps = %s:%s/%s }' \
+                "$dbtype" "$cfdir" "$snitab"
+            printf '\t-o { syslog_name = postfix/sni-test }'
+            )"
+        # postfix reload; sleep 1
+        # ( sleep 1; printf "QUIT\r\n") |
+            openssl s_client -brief -starttls smtp \
+                -connect "127.0.0.1:$port" \
+                -sigalgs "$rsasig" -cipher aRSA \
+                -verify 1 -verify_return_error \
+                -dane_tlsa_domain "$fqdn" \
+                -dane_tlsa_rrdata "3 1 1 $rh" &&
+            printf "OK: Got expected RSA SNI chain\n" ||
+            printf "ERROR: Unexpected RSA server certificate\n" >&2
+        # ( sleep 1; printf "QUIT\r\n") |
+            openssl s_client -brief -starttls smtp \
+                -connect "127.0.0.1:$port" \
+                -sigalgs "$ecsig" -cipher aECDSA \
+                -verify 1 -verify_return_error \
+                -dane_tlsa_domain "$fqdn" \
+                -dane_tlsa_rrdata "3 1 1 $eh" &&
+            printf "OK: Got expected EC SNI chain\n" ||
+            printf "ERROR: Unexpected EC SNI certificate\n" >&2
+        # postconf -MX "127.0.0.1:$port/inet"
+        # postfix reload
+
+With a dual algorithm RSA + ECDSA chain also successful (for most users just
+single-algorithm RSA is the better choice), it is time to check whether the
+OpenSSL runtime supports SNI also for post-quantum algorithm keys. This
+requires OpenSSL 3.5 or later, earlier versions don't support the MMLL--DDSSAA
+algorithm needed for this test:
+
+        # cfdir=$(postconf -dxh config_directory)
+        # cd "$cfdir"
+        # mchain="test-mldsa-chain.pem"
+        # mlsig="mldsa44"
+        # fqdn=sni-test.localhost
+        # dbtype=$(postconf -xh default_database_type)
+        # snitab=sni-test-table
+        # openssl genpkey -algorithm ml-dsa-44 -out "$mchain"
+        # openssl req -new -x509 -key "$mchain" -subj "/CN=$fqdn" \
+            -addext "basicConstraints = critical,CA:false" \
+            -addext "extendedKeyUsage = serverAuth" \
+            -addext "subjectAltName = DNS:$fqdn" >> "$mchain"
+        # mh=$(openssl pkey -in "$mchain" -pubout -outform DER |
+            openssl dgst -sha256 | sed 's/.*= *//')
+        # (
+            umask 077
+            printf "%s\t%s\n" "$fqdn" "$cfdir/$mchain" > "$snitab"
+          )
+        # postmap -F "${dbtype}:${snitab}"
+        # port=$(perl -MIO::Socket -le '
+            print IO::Socket::INET->new(
+                Listen => 1,
+                ReuseAddr => 1,
+                LocalHost => "127.0.0.1",
+                LocalPort => 0)->sockport()
+                ')
+        # postconf -M "$(
+            printf '%s/inet = %s inet n - n - - smtpd' \
+                "127.0.0.1:$port" "127.0.0.1:$port"
+            printf '\t-o { tls_server_sni_maps = %s:%s/%s }' \
+                "$dbtype" "$cfdir" "$snitab"
+            printf '\t-o { syslog_name = postfix/sni-test }'
+            )"
+        # postfix reload; sleep 1
+        # ( sleep 1; printf "QUIT\r\n") |
+            openssl s_client -brief -starttls smtp \
+                -connect "127.0.0.1:$port" \
+                -sigalgs "$mlsig" -tls1_3 \
+                -verify 1 -verify_return_error \
+                -dane_tlsa_domain "$fqdn" \
+                -dane_tlsa_rrdata "3 1 1 $mh" &&
+            printf "OK: Got expected ML-DSA SNI chain\n" ||
+            printf "ERROR: Unexpected ML-DSA server certificate\n" >&2
+        # postconf -MX "127.0.0.1:$port/inet"
+        # postfix reload
+
+If all went well, your OpenSSL runtime working SNI support for also for newer
+public key algorithms, such as MMLL--DDSSAA. If the test failed, and the Postfix logs
+show that the test Postfix SMTP server failed with a segfault, your OpenSSL
+runtime has not yet been patched. The test is not viable with OpenSSL 3.4 or
+earlier, which don't include MMLL--DDSSAA support, and is expected to work with
+OpenSSL 4.0, which should be free of the underlying defect when initially
+released.
 
 SSMMTTPP CClliieenntt ssppeecciiffiicc sseettttiinnggss
 
