snapshot-20001005

diff --git a/postfix/conf/postfix-script-nosgid b/postfix/conf/postfix-script-nosgid
--- a/postfix/conf/postfix-script-nosgid
+++ b/postfix/conf/postfix-script-nosgid
@@ -227,6 +227,31 @@ check)
 		done
 	done
 
+	# Look for incomplete upgrades.
+
+	test -f $config_directory/master.cf || {
+		$FATAL no $config_directory/master.cf file found
+		exit 1
+	}
+	grep 'flush.*flush' $config_directory/master.cf >/dev/null || {
+		$WARN adding missing entry for flush service to master.cf
+		cat >>$config_directory/master.cf <<EOF
+flush	  unix	-	-	n	1000?	0	flush
+EOF
+	}
+	found=`$command_directory/postconf -h hash_queue_names`
+	missing=
+	(echo "$found" | grep active >/dev/null) || missing="$missing active"
+	(echo "$found" | grep bounce >/dev/null) || missing="$missing bounce"
+	(echo "$found" | grep defer >/dev/null)  || missing="$missing defer"
+	(echo "$found" | grep flush >/dev/null)  || missing="$missing flush"
+	test -n "$missing" && {
+		$WARN fixing main.cf hash_queue_names for missing $missing
+		$command_directory/postconf -e hash_queue_names="$found$missing"
+	}
+
+	# See if all queue files are in the right place.
+
 	$command_directory/postsuper || exit 1
 
 	find corrupt -type f -exec $WARN damaged message: {} \;
