postfix-3.1-20160213

diff --git a/postfix/conf/postfix-tls-script b/postfix/conf/postfix-tls-script
--- a/postfix/conf/postfix-tls-script
+++ b/postfix/conf/postfix-tls-script
@@ -6,9 +6,9 @@
 # SUMMARY
 #	Postfix TLS management
 # SYNOPSIS
-#	\fBpostfix tls\fR \fIsubcommand\fB ...\fR
+#	\fBpostfix tls\fR \fIsubcommand\fR
 # DESCRIPTION
-#	The "\fBpostfix tls \fIsubcommand\fB ...\fR" feature enables
+#	The "\fBpostfix tls \fIsubcommand\fR" feature enables
 #	opportunistic TLS in the Postfix SMTP client or server, and
 #	manages Postfix SMTP server private keys and certificates.
 #
@@ -23,7 +23,9 @@
 #	\fBtls_random_source\fR configuration parameter (typically,
 #	/dev/urandom).  Prepend \fBdev:\fR to device paths or
 #	\fBegd:\fR to EGD socket paths.
-# .IP "\fBenable-server\fR [\fB-r \fIrandsource\fR] [\fB-a \fIalgorithm\fR] [\fB-b \fIbits\fR] [\fIhostname\fB ...\fR]"
+# .sp
+#	See also the \fBall-default-client\fR subcommand.
+# .IP "\fBenable-server\fR [\fB-r \fIrandsource\fR] [\fB-a \fIalgorithm\fR] [\fB-b \fIbits\fR] [\fIhostname\fB...\fR]"
 #	Create a new private key and self-signed server certificate
 #	and enable opportunistic TLS in the Postfix SMTP server,
 #	if all SMTP server TLS settings are at their default values.
@@ -33,7 +35,9 @@
 #	The \fIrandsource\fR parameter is as with \fBenable-client\fR
 #	above, and the remaining options are as with \fBnew-server-key\fR
 #	below.
-# .IP "\fBnew-server-key\fR [\fB-a \fIalgorithm\fR] [\fB-b \fIbits\fR] [\fIhostname\fB ...\fR]"
+# .sp
+#	See also the \fBall-default-server\fR subcommand.
+# .IP "\fBnew-server-key\fR [\fB-a \fIalgorithm\fR] [\fB-b \fIbits\fR] [\fIhostname\fB...\fR]"
 #	Create a new private key and self-signed server certificate,
 #	but do not deploy them. Log and display commands to deploy
 #	the new key and corresponding certificate.  Also log and
@@ -85,12 +89,12 @@
 #	be the first certificate in the chain file.  Overwrite and
 #	deploy the file with the original self-signed certificate
 #	that was generated together with the key.
-# .IP "\fBnew-server-cert\fR [\fB-a \fIalgorithm\fR] [\fB-b \fIbits\fR] [\fIhostname\fB ...\fR]"
+# .IP "\fBnew-server-cert\fR [\fB-a \fIalgorithm\fR] [\fB-b \fIbits\fR] [\fIhostname\fB...\fR]"
 #	This is just like \fBnew-server-key\fR except that, rather
 #	than generating a new private key, any currently deployed
 #	private key is copied to the new key file.  Thus if you're
 #	publishing DANE TLSA "3 1 1" or "3 1 2" records, there is
-#	no need to update DNS records.  The \fIalgorithm\fB and
+#	no need to update DNS records.  The \fIalgorithm\fR and
 #	\fIbits\fR arguments are used only if no key of the same
 #	algorithm is already configured.
 # .sp
@@ -113,8 +117,7 @@
 #	deployed any obsolete keys and certificates may be removed
 #	by hand.   The \fIkeyfile\fR and \fIcertfile\fR filenames
 #	are relative to the Postfix configuration directory.
-# .IP "\fBoutput-server-csr\fR [\fB-k \fIkeyfile\fR] [\fIhostname\fB
-# ...\fR]"
+# .IP "\fBoutput-server-csr\fR [\fB-k \fIkeyfile\fR] [\fIhostname\fB...\fR]"
 #	Write to stdout a certificate signing request (CSR) for the
 #	specified \fIkeyfile\fR.
 # .sp
@@ -127,7 +130,7 @@
 #	Zero or more \fIhostname\fR values can be specified.  The
 #	default \fIhostname\fR is the value of \fBmyhostname\fR
 #	main.cf parameter.
-# .IP "\fBoutput-server-tlsa\fR [\fB-h \fIhostname\fR] [\fIkeyfile\fB ...\fR]"
+# .IP "\fBoutput-server-tlsa\fR [\fB-h \fIhostname\fR] [\fIkeyfile\fB...\fR]"
 #	Write to stdout a DANE TLSA RRset suitable for a port 25
 #	SMTP server on host \fIhostname\fR with keys from any of
 #	the specified \fIkeyfile\fR values.  The default \fIhostname\fR
@@ -143,10 +146,25 @@
 # .sp
 #	The default \fIkeyfile\fR list consists of the two supported
 #	algorithms \fBrsa\fR and \fBecdsa\fR.
+# AUXILIARY COMMANDS
+# .IP "\fBall-default-client\fR"
+#	Exit with status 0 (success) if all SMTP client TLS settings are
+#	at their default values.  Otherwise, exit with a non-zero status.
+#	This is typically used as follows:
+# .sp
+#	\fBpostfix tls all-default-client &&
+#		postfix tls enable-tls-client\fR
+# .IP "\fBall-default-server\fR"
+#	Exit with status 0 (success) if all SMTP server TLS settings are
+#	at their default values.  Otherwise, exit with a non-zero status.
+#	This is typically used as follows:
+# .sp
+#	\fBpostfix tls all-default-server &&
+#		postfix tls enable-tls-server\fR
 # CONFIGURATION PARAMETERS
 # .ad 
 # .fi
-#	The "\fBpostfix tls \fIsubcommand\fB ...\fR" feature reads
+#	The "\fBpostfix tls \fIsubcommand\fR" feature reads
 #	or updates the following configuration parameters.
 # .IP "\fBcommand_directory (see 'postconf -d' output)\fR"
 #	The location of all postfix administrative commands.
@@ -189,6 +207,14 @@
 # SEE ALSO
 #	master(8) Postfix master program
 #	postfix(1) Postfix administrative interface
+# README FILES
+# .ad
+# .fi
+#	Use "\fBpostconf readme_directory\fR" or
+#	"\fBpostconf html_directory\fR" to locate this information.
+# .na
+# .nf
+#	TLS_README, Postfix TLS configuration and operation
 # LICENSE
 # .ad
 # .fi
@@ -218,6 +244,26 @@ INFO="$LOGGER -p info"
 WARN="$LOGGER -p warn"
 ERROR="$LOGGER -p error"
 FATAL="$LOGGER -p fatal"
+
+# Overwrite SMTP client and server settings only when these are at defaults.
+client_settings="
+    smtp_use_tls 
+    smtp_enforce_tls 
+    smtp_tls_enforce_peername 
+    smtp_tls_security_level 
+    smtp_tls_cert_file
+    smtp_tls_dcert_file
+    smtp_tls_eccert_file
+"
+
+server_settings="
+    smtpd_use_tls 
+    smtpd_enforce_tls 
+    smtpd_tls_security_level 
+    smtpd_tls_cert_file
+    smtpd_tls_dcert_file
+    smtpd_tls_eccert_file
+"
 
 #
 # Can't do much without these in place.
@@ -677,11 +723,11 @@ init_random_source() {
     fi
 }
 
+# Don't be too clever by half.
 all_default() {
-    prefix=$1; shift
     for var in "$@"
     do
-	val=`$postconf -nh "${prefix}${var}"`
+	val=`$postconf -nh "${var}"`
 	if [ -n "$val" ]; then return 1; fi
     done
     return 0
@@ -781,8 +827,7 @@ new_server_cert() {
 }
 
 enable_client() {
-    if all_default smtp_ \
-	use_tls enforce_tls tls_enforce_peername tls_security_level tls_cert_file
+    if all_default ${client_settings}
     then
 	set -- \
 	    "smtp_tls_security_level = may" \
@@ -810,8 +855,7 @@ enable_server() {
     algo=$1; shift
     bits=$1; shift
 
-    if all_default smtpd_ \
-	use_tls enforce_tls tls_security_level tls_cert_file
+    if all_default ${server_settings}
     then
 	# algo bits keyfile deploy [hostnames ...]
 	new_server_cert "${algo}" "${bits}" "" "enable" "$@" || return 1
@@ -1041,9 +1085,33 @@ output-server-tlsa)
 	fi
 	;;
 
+all-default-client)
+	cmd=$1; shift; OPTIND=1
+
+	# No arguments for all-default-client
+	if [ $# -ge "${OPTIND}" ]; then
+	    $FATAL "usage: postfix tls $cmd"
+	    exit 1
+	fi
+
+	all_default ${client_settings} || exit 1
+	;;
+
+all-default-server)
+	cmd=$1; shift; OPTIND=1
+
+	# No arguments for all-default-server
+	if [ $# -ge "${OPTIND}" ]; then
+	    $FATAL "usage: postfix tls $cmd"
+	    exit 1
+	fi
+
+	all_default ${server_settings} || exit 1
+	;;
+
 *)
 	$ERROR "unknown tls command: '$1'"
-	$FATAL "usage: postfix tls enable-client (or enable-server, new-server-key, new-server-cert, deploy-server-cert, output-server-csr, output-server-tlsa)"
+	$FATAL "usage: postfix tls enable-client (or enable-server, new-server-key, new-server-cert, deploy-server-cert, output-server-csr, output-server-tlsa, all-default-client, all-default-server)"
 	exit 1
 	;;
 
