postfix-3.4-20190129

diff --git a/postfix/conf/postfix-script b/postfix/conf/postfix-script
--- a/postfix/conf/postfix-script
+++ b/postfix/conf/postfix-script
@@ -139,7 +139,7 @@ start|start-fg)
 		# Foreground this so it can be stopped. All inodes are cached.
 		$daemon_directory/postfix-script check-warn
 	fi
-	$INFO starting the Postfix mail system
+	$INFO starting the Postfix mail system || exit 1
 	case $1 in
 	start)
 	    # NOTE: wait in foreground process to get the initialization status.
@@ -158,7 +158,7 @@ start|start-fg)
 		 1) exec $daemon_directory/master -i
 		    $FATAL "cannot start-fg the master daemon"
 		    exit 1;;
-		 *) $daemon_directory/master;;
+		 *) $daemon_directory/master -s;;
 		esac
 		;;
 	     *) $FATAL "start-fg does not support multi_instance_directories"
@@ -266,6 +266,18 @@ check-fatal)
 	test -f $config_directory/master.cf || {
 		$FATAL no $config_directory/master.cf file found
 		exit 1
+	}
+
+	maillog_file=`$command_directory/postconf -h maillog_file` || {
+		$FATAL cannot execute $command_directory/postconf!
+		exit 1
+	}
+	test -n "$maillog_file" && {
+		$command_directory/postconf -M postlog/unix-dgram 2>/dev/null \
+		    | grep . >/dev/null || {
+			$FATAL "missing 'postlog' service in master.cf - run 'postfix upgrade-configuration'"
+			exit 1
+		}
 	}
 
 	# See if all queue files are in the right place. This is slow.
