postfix-2.4-20061209

diff --git a/postfix/conf/post-install b/postfix/conf/post-install
--- a/postfix/conf/post-install
+++ b/postfix/conf/post-install
@@ -588,16 +588,16 @@ EOF
     # would be accepted by a previous Postfix version.
     # This safety net is also documented in LOCAL_RECIPIENT_README.
 
-    unknown_local=unknown_local_recipient_reject_code
-    has_lrm=`$POSTCONF -c $config_directory -n local_recipient_maps`
-    has_lrjc=`$POSTCONF -c $config_directory -n $unknown_local`
-
-    if [ -z "$has_lrm" -a -z "$has_lrjc" ]
-    then
-	echo SAFETY: editing main.cf, setting $unknown_local=450.
-	echo See the LOCAL_RECIPIENT_README file for details.
-	$POSTCONF -c $config_directory -e "$unknown_local = 450" || exit 1
-    fi
+#    unknown_local=unknown_local_recipient_reject_code
+#    has_lrm=`$POSTCONF -c $config_directory -n local_recipient_maps`
+#    has_lrjc=`$POSTCONF -c $config_directory -n $unknown_local`
+#
+#    if [ -z "$has_lrm" -a -z "$has_lrjc" ]
+#    then
+#	echo SAFETY: editing main.cf, setting $unknown_local=450.
+#	echo See the LOCAL_RECIPIENT_README file for details.
+#	$POSTCONF -c $config_directory -e "$unknown_local = 450" || exit 1
+#    fi
 
     # Add missing proxymap service to master.cf.
 
@@ -656,6 +656,15 @@ EOF
 	echo Editing $config_directory/master.cf, adding missing entry for tlsmgr service
 	cat >>$config_directory/master.cf <<EOF || exit 1
 tlsmgr    unix  -       -       n       1000?   1       tlsmgr
+EOF
+    }
+
+    # Add missing retry service to master.cf.
+
+    grep '^retry.*error' $config_directory/master.cf >/dev/null || {
+	echo Editing $config_directory/master.cf, adding missing entry for retry service
+	cat >>$config_directory/master.cf <<EOF || exit 1
+retry     unix  -       -       n       -       -       error
 EOF
     }
 
